theme: jekyll-theme-cayman
title: Digital Systems Design Lab
description: Labs

footer-links:
  dribbble: 
  email: tianzhao@stanford.edu
  github: https://github.com/stanford-ppl/spatial-lang
  
page-img: "/img/spatial.jpg"

font:
  # The normal (roman) font face to use.
  # Style can be specified to pick a specific face.
  normal:
    family: "Fira Code"
    style: Retina

  # The bold font face
  bold:
    family: "Fira Code"

  # The italic font face
  italic:
    family: "Fira Code"
